#html_validator.yml
name: HTML5 Validator

on: [pull_request, push]

jobs:
  check-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: HTML5 Validator 🧪
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: html5/
          blacklist: invalid
